--1)select * from country WHERE country LIKE 'A%a';
--2)select * from country where length(country) >= 6 and country like '%n';
--3)select * from film where length(title) >= 4 and title ILIKE '%t%';
--4)select * from film where title like 'C%' and length >90 and rental_rate =2.99;
